=== bedroesb/FAIRPlus/RESOLUTE/trancriptomics/schemas/minseqe/schema/investigation_schema.json
{
  "id": "https://w3id.org/mircat/minseqe/schema/investigation_schema.json",
  "$schema": "http://json-schema.org/draft-04/schema",
  "title" : "MINSEQE investigation schema",
  "version" : "1.0",
  "description" : "JSON-schema representing an investigation using sequencing techniques. A planned activity that involves one or more studies.",
  "type" : "object",
  "properties" : {
    "@context": {
      "description": "The JSON-LD context",
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        },
        {
          "type": "array"
        }
      ]
    },
    "@id": {
      "description": "The JSON-LD identifier",
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "description": "The JSON-LD type",
      "type": "string",
      "enum": [
        "Investigation"
      ]
    },
    "identifier" : {
      "description": "Primary identifier for the investigation. Ideally, a persistent identifier but an internal user identifier at a minimum.",
      "type" : "string"
    },
    "identifierSource" : {
      "description": "Information about the organisation or namespace responsible for creating and maintaining the identifier.",
      "type" : "string"
    },
    "title" : {
      "description": "The title of the investigation.",
      "type" : "string"
    },
    "description" : {
      "description": "A textual narrative comprised of one or more statements about the investigation.",
      "type" : "string"
    },
    "contacts" : {
      "description": "The person(s) who contributed to the investigation, such as the Principal Investigator, corresponding author in related publications or other researchers involved.",
      "type" : "array",
      "items" : {
        "$ref": "person_schema.json#"

      }
    },
    "studies" : {
      "description": "The studies associated with the Investigation.",
      "type" : "array",
      "items" : {
        "$ref": "study_schema.json#"

      }
    },
    "publications" : {
      "description": "Scholarly articles associated with the investigation, usually describing the methods applied and conclusions reached by the investigation.",
      "type" : "array",
      "items" : {
        "$ref": "publication_schema.json#"
      }
    },
    "acknowledges" : {
      "description": "The grant(s) which funded and supported the investigation.",
      "type": "array",
      "items": {
        "$ref": "fund_schema.json#"
      }
    },
    "conclusions" : {
      "description": "A set of statements summarizing the findings of the investigation. It could be a URI referring to a nanopublication.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dates": {
      "description": "Dates relevant to the investigation.",
      "type": "array",
      "items": {
        "$ref": "https://w3id.org/dats/schema/date_info_schema.json"
      }
    },
    "MINSEQEversion": {
      "description": "The version of MINSEQE this dataset description should be compliant with.",
      "type": "string"
    },
    "MINSEQEcompliance": {
      "description": "The result of the validation for MINSEQE compliance.",
      "type": "string"
    }
  },
  "additionalProperties": false
}

=== bedroesb/FAIRPlus/RESOLUTE/transcriptomics/data/RESOLUTE_transcriptomics_metadata_MINSEQE.json
{
	"title": "RESOLUTE Transcriptome of RESOLUTE parental cell lines",
	"description": "To enable successful SLC function deorphanization we aimed to select minimal number of cell lines covering expression of as many SLCs as possible based on publicly available RNA-Seq dataset of 675 cell lines (Klijn C. et al, Nat. Biotechnol. 2015). A set of 6 adherent human cell lines (HCT116, HuH-7, LS-180, MDA-MB-468, SK-MEL-28, 1321-N1) cumulatively covers expression of about 80 % of all SLCs (TPM  1). These cell lines will be used to generate SLC-knockout and SLC-overexpressing single cell clones. Additionally, Jump In T-REx HEK 293 cells will be used for generating SLC-overexpression cell lines.",
	"contacts": [{
			"lastName": "Viollet",
			"firstName": "Coralie"
			
		},
		{
			"lastName": "Sedlyarov",
			"firstName": "Vitaly",
			"email":"VSedlyarov@cemm.oeaw.ac.at"
		},
		{
			"lastName": "Goldmann",
			"firstName": "Ulrich",
			"email":"UGoldmann@cemm.oeaw.ac.at"
		},
		{
			"lastName": "Lackner",
			"firstName": "Daniel",
			"email": "dlackner@re-solute.eu",
			"address": "Lazarettgasse 14, AKH BT 25.3 1090 Vienna, Austria",
			"affiliation": [{"name":"CeMM Research Center for Molecular Medicine of the Austrian Academy of Sciences"}],
			"roles": "scientific project manager"
		},
		{
			"lastName": "Superti-Furga",
			"firstName": "Giulio",
			"email": "gsuperti@cemm.oeaw.ac.at",
			"affiliation": [{"name":"Pfizer Ltd."}],
			"roles": "Academic Project coordinator"
		},
		{
			"lastName": "Steppan",
			"firstName": "Claire",
			"email": "Claire.M.Steppan@pfizer.com",
			"affiliation": [{"name":"CeMM Research Center for Molecular Medicine of the Austrian Academy of Sciences"}],
			"roles": "EFPIA Project Leader"
		}
	],
	"studies": [{
		"title": "RNA-Seq measurements of parental cell lines",
		"description": "Transcription profiling of 6 (+1) Resolute cell lines.",
		"studyType": "RNASeq",
		"contacts": [{
				"lastName": "Viollet",
				"firstName": "Coralie",
				"affiliation": [{"name":"Boehringer Ingelheim"}]
			},
			{
				"lastName": "Sedlyarov",
				"firstName": "Vitaly",
				"email":"VSedlyarov@cemm.oeaw.ac.at",
				"affiliation": [{"name":"CeMM Research Center for Molecular Medicine of the Austrian Academy of Sciences"}]
			}
		],
		"assays": [{
			"sample_input": "cell line HuH-7",
			"library_source": "TRANSCRIPTOMIC",
			"library_layout": "SINGLE",
			"library_strategy": "RNA-Seq",
			"sequencing_platform": {
				"platform": "Illumina",
				"model": "Illumina HiSeq 4000"
			},
			"data_output": {
				"filename": "180927_J00151_0269_AH2C25BBXY_716_{SampleNr}_SXX_LXXX_R1_001.fastq",
				"file_format": "fastq"
			}}],
			"protocols": [{
					"name": "cell culture",
					"protocol_description": "cell line origin: JCRB; Growthmedia: DMEM; 10 % FCS; Pen-Strep; tested for mycoplasma;STR profiling was performed for all cell lines to confirm identity",
					"protocol_type": "cell culture"
				},
				{
					"name": "RNA isolation",
					"protocol_description": "Cells (1 x 106 ) were washed 1x with PBS and lysed directly on the dish with RLT buffer (Qiagen) supplemented with 0.143 M -Mercaptoethanol.RNA was isolated using RNeasy Mini Kit (Qiagen) including DNase I digestion according to the manufacture’s protocol. RNA quality was accessed using Bioanalyzer (Agilent). All samples showed high RNA integrity, i.e. RIN 9.6  0.21 (mean  sd)",
					"protocol_type": "RNA isolation"
				},
				{
					"name": "library preparation",
					"protocol_description": "mRNA-Seq libraries were prepared using NEBNext Ultra II Directional RNA Library Prep Kit for Illumina, together with rRNA depletion (NEB).",
					"protocol_type": "library preparation"
				},
				{
					"name": "data quality control",
					"protocol_url": "FastQC, RNA-Seq reads of high quality in all samples. Standard trimming/clipping should be performed.",
					"protocol_type": "data quality control"
				}
			],
			"processed_data_file": [{
					"analysis_type": "REFERENCE_ALIGNMENT",
					"software": "STAR (2.6.1a)",
					"input_files": "Raw reads in fastq.gz format from ‘1. RNA-Seq measurements of parental cell lines",
					"reference_genome": "hg38 genome",
					"output_files": [{
							"filename": "{i}_sorted.bam i in 1:21",
							"file_format": "bam"
						},
						{
							"filename": "{i}_sorted.bai i in 1:21",
							"file_format": "bai"
						}
					]
				},
				{
					"analysis_type": "REFERENCE_ALIGNMENT",
					"software": "kallisto (0.44.0)",
					"reference_genome": " ENSEMBL GRCh38 cDNA transcriptome",
					"output_files": {
						"filename": " {i}_abundance.tsv, {i}_abundance.h5 i in 1:21"
					}
				}
			],
		"conclusions": "We generated transcriptome profile for 7 cell line which will be used in course of RESOLUTE project. RNA-Seq based transcriptome profile of 1321-N1 and Jump In T-REx HEK 293, to our knowledge, have not been published before. Transcriptome of the RESOLUTE cell lines would be interesting to SLC community as a minimal set of cell lines covering maximal number of expressed SLC (approx. 80%)."
		}
	],
	"acknowledges": [{
		"name": "RESOLUTE – Research Empowerment on SOLUTE carriers"
	}]
}
